language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

matrix:
  include:
  - php: 5.6
    env: SYMFONY_VERSION='^2'
  - php: 5.6
    env: SYMFONY_VERSION='^3'
  - php: 7.0
    env: SYMFONY_VERSION='^3'
  - php: 7.1
    env: SYMFONY_VERSION='^3' PHPUNIT_ARGS='--testdox'
  - php: 7.2
    env: SYMFONY_VERSION='^3' PHPUNIT_ARGS='--testdox'
  - php: 7.2
    env: SYMFONY_VERSION='^4' COVERAGE='' PHPCS='' PHPSTAN='' PHPUNIT_ARGS='--testdox --coverage-text --coverage-clover=build/phpunit.coverage.xml'

before_install:
  - if [ -z "${COVERAGE+x}" ];then echo 'disabling xdebug'; phpenv config-rm xdebug.ini || true;fi

before_script:
  - composer require --dev --no-update dunglas/symfony-lock=$SYMFONY_VERSION
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit $PHPUNIT_ARGS --disallow-test-output --colors=always
  - if [ -n "${PHPCS+x}" ];then php vendor/bin/phpcs;fi
  - if [ -n "${PHPSTAN+x}" ];then sh .travis.analyze.sh ;fi

after_script:
  - if [ -n "${COVERAGE+x}" ];then sh .travis.coverage.sh;fi
